### ISSUE TITLE
eeee

### ISSUE THREAD

**Issue by klaufel** [klaufel/next-skeleton#12]
e

**Comment by ghost** [comment]
### 🚀 Deploy this branch on stage environment
View more info for [deploy actions ↗︎](${{ github.server_url }}/${{ github.repository }}/actions)
| Name | Status | Preview | Deploy |
| :- | :- | :- | :- |
| **stage-2** | ✅ Active | [View live site](https://stage2-marketplace.blommarket.com/) | [Deploy branch on stage-2 →](${{ github.server_url }}/${{ github.repository }}}/actions/runs/ci?stage2)
| **stage-3** | ✅ Active | [View live site](https://stage3-marketplace.blommarket.com/) | [Deploy branch on stage-3 →](${{ github.server_url }}/${{ github.repository }}}/actions/runs/ci?stage3)
| **stage-4** | ✅ Active | [View live site](https://stage4-marketplace.blommarket.com/) | [Deploy branch on stage-4 →](${{ github.server_url }}/${{ github.repository }}}/actions/runs/ci?stage4)
| **stage-5** | ✅ Active | [View live site](https://stage5-marketplace.blommarket.com/) | [Deploy branch on stage-5 →](${{ github.server_url }}/${{ github.repository }}}/actions/runs/ci?stage5)

📦 Current branch: [github.event.pull_request.head.ref](${{ github.server_url }}/${{ github.repository }}/tree/github.event.pull_request.head.ref)

**Comment by klaufel** [comment]
efef

**Comment by klaufel** [comment]
efef
